### ISSUE TITLE
Добавить тесты для утилит

### ISSUE THREAD

**Issue by martis-git** [actool/eslint-plugin-actool#63]
**Problem** 

У нас имеются базовые тесты для правил, но нет тестов для самих утилит, которые используются этими тестами.

Из-за этого нет полной уверенности, что плагин полностью работает корректно

**Solution (optional)**

- На каждый файл утилиту - реализовать тестовый файл  в директории `tests/lib/utils/` 
   - На каждую функцию внутри файла - должен быть свой отдельный внутренний тест
- Реализовать тесты для утилит (в скобках указано кол-во внутренних тестов):
   - `revision.js` (4)
   - `commits-distance.js` (1)
   - `array.js` (1)
   - `validate.js` (2)

> Как я это вижу:
> ```js
> describe("util > revision > parseLineRevision", () => {
>    it("valid", () => {
>      ...
>      const actual = parseLineRevision(validRevision));
>      assert.equal(actual, expected);  // equal условный, т.к. нам ведь надо сравнивать объект - возможно надо пройтись по полям
>    });
> });
> ```

**Additional context (optional)**

- Директория для тестов утилит
   <img src="https://user-images.githubusercontent.com/42924400/101245555-c9da3700-371e-11eb-9595-64ef896ac820.png" height=100 />
- [Дока по тестированию на mocha](https://learn.javascript.ru/testing) которая в принципе должна помочь реализовать тесты (mocha у нас в проекте уже есть судя по package.json)
- Для тестов коммитов - есть файл в [test/lib/fixtures/](https://github.com/actool/eslint-plugin-actool/tree/master/tests/lib/fixtures) - при необходимости можно добавить
- Если будут вопросы - лучше пиши сразу

**Comment by lyf2000** [comment]
**ПРОБЛЕМА**: Не смог создать моки для методов, которые вызываются внутри тестируемых функций

Что не протестировано:

- revision.js [`getLineCommit`, `getBlockLastCommit`]
- commits-distance.js [`getCommitsDiff`] - тут чисто метод, которых достает строки по git в cmd
- validate [`validateDiffByCommits`] - переписать `commitsHistory`

**Comment by lyf2000** [comment]
PR
https://github.com/actool/eslint-plugin-actool/pull/76
